### ISSUE TITLE
Crashes when using non existant callback

### ISSUE THREAD

**Issue by AGraber** [pBlueG/SA-MP-MySQL#189] opened 2018-02-11 19:36 UTC
Could be an issue/bug with `amx_FindPublic`. For some reason it's returning negative indexes, and they go as valid because they aren't equal to AMX_ERR_NONE

Example with OnQueryError:
```
[10:35:02] [DEBUG] CCallback::Create(amx=0x95d3ba8, name='OnQueryError', format='dsssd)
[10:35:02] [DEBUG] CCallback::Create - callback index for 'OnQueryError': -10051
[10:35:02] [DEBUG] processing specifier 'd'
[10:35:02] [DEBUG] retrieved and pushed value '1064'
[10:35:02] [DEBUG] processing specifier 's'
[10:35:02] [DEBUG] retrieved and pushed value 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''3' at line 1'
[10:35:02] [DEBUG] processing specifier 's'
[10:35:02] [DEBUG] retrieved and pushed value ''
[10:35:02] [DEBUG] processing specifier 's'
[10:35:02] [DEBUG] retrieved and pushed value 'UPDATE `CUENTA` SET `NAME` = 'Alexx_Franzese', `BNAME` = 'Alexx_Franzese' WHERE `ID` = '3'
[10:35:02] [DEBUG] processing specifier 'd'
[10:35:02] [DEBUG] retrieved and pushed value '1'
[10:35:02] [INFO] Callback 'OnQueryError' set up for delayed execution.
[10:35:02] [DEBUG] created delayed callback with 5 parameters
[10:35:02] [DEBUG] CCallback::Execute(amx=0x95d3ba8, index=-10051, num_params=5)
(crashed here)
```

Another example with a Callback I forgot to declare:
```
[00:02:13] [DEBUG] mysql_tquery(1, "SELECT * FROM `PHONE_MESSAGES` WHERE `FROM` = '6098264' ORDER BY `DATE` DESC LIMIT 10;", "PhoneLoadSentMessages", "i") (D:\Documentos\InfinityU\GM\gamemodes\srp.pwn:9858 -> D:\Documentos\InfinityU\GM\gamemodes\srp.pwn:13208)
[00:02:13] [DEBUG] CCallback::Create(amx=0x8f5fbc0, name='PhoneLoadSentMessages', format='i', params=0xf3c0f328, param_offset=5)
[00:02:13] [DEBUG] CCallback::Create - callback index for 'PhoneLoadSentMessages': -10065
[00:02:13] [DEBUG] processing specifier 'i' with parameter index 0
[00:02:13] [DEBUG] retrieved and pushed value '15'
[00:02:13] [INFO] Callback 'PhoneLoadSentMessages' set up for delayed execution.
[00:02:13] [DEBUG] created delayed callback with 1 parameter
[00:02:13] [DEBUG] CHandle::Execute(this=0x8f62fa8, type=1, query=0x98247f4)
[00:02:13] [DEBUG] CHandle::Execute - return value: true
[00:02:13] [DEBUG] mysql_tquery: return value: '1' (D:\Documentos\InfinityU\GM\gamemodes\srp.pwn:9858 -> D:\Documentos\InfinityU\GM\gamemodes\srp.pwn:13208)
[00:02:13] [DEBUG] CConnection::Execute(query=0x98247f4, this=0xf2fe6008, connection=0x90e0bf8)
[00:02:13] [DEBUG] CQuery::Execute(this=0x98247f4, connection=0x90e0bf8)
[00:02:13] [INFO] query "SELECT * FROM `PHONE_MESSAGES` WHERE `FROM` = '6098264' ORDER BY `DATE` DESC LIMIT 10;" successfully executed within 0.959 milliseconds
[00:02:13] [DEBUG] CResultSet::Create(connection=0x90e0bf8, query_str='SELECT * FROM `PHONE_MESSAGES` WHERE `FROM` = '6098264' ORDER BY `DATE` DESC LIMIT 10;')
[00:02:13] [DEBUG] created new resultset '0xf2600868'
[00:02:13] [DEBUG] fetched MySQL result '0xf26006b0'
[00:02:13] [DEBUG] allocated 0 bytes for PAWN result
[00:02:13] [DEBUG] CCallback::Execute(amx=0x8f5fbc0, index=-10065, num_params=1)
(crashed here)
```

**Comment by maddinat0r** [comment] 2018-02-11 20:04
What plugins and includes are you using in your gamemode and filterscripts?

**Comment by AGraber** [comment] 2018-02-11 20:29
I'm currently using this:

```
#include <a_samp>
#include <a_mysql>
#include <a_http>
#include <crashdetect>
#include <streamer>
#include <sscanf2>
#include <Pawn.CMD>
#include <Pawn.Regex>
#include <crashdetect>
#include <discord-connector>
```

I'm also compiling with -d3, and just in case, the only case in which I use #emit on the entire script:
```
`SendClientMessageEx(playerid, color, form[], {Float, _}: ...) 
{
    #pragma unused form

    static
        tmp[145]
    ;
    new
        t1 = playerid,
        t2 = color
    ;
    const
        n4 = -4,
        n16 = -16,
        size = sizeof tmp
    ;
    #emit stack 28
    #emit push.c size
    #emit push.c tmp
    #emit stack n4
    #emit sysreq.c format
    #emit stack n16

    return (t1 == -1 ? (SendClientMessageToAll(t2, tmp)) : (SendClientMessage(t1, t2, tmp)) );
}
```

**Comment by maddinat0r** [comment] 2018-02-11 20:45
This might actually be a regression introduced in R40:
https://github.com/pBlueG/SA-MP-MySQL/blob/b89d115fefb465eaf6d1562ef6fa94596c0050e7/src/CCallback.cpp#L43
This "problem" is caused by the sampgdk, because it hooks `amx_FindPublic ` and returns negative indices on publics which are not found: https://github.com/Zeex/sampgdk/blob/33dc79f555e6b46744a02916a730c31f20819faa/lib/sampgdk/internal/amxhooks.c#L132-L155

**Comment by maddinat0r** [comment] 2018-02-11 20:49
If I recall correctly, fixing this will end up breaking plugins/C++ gamemodes that use the MySQL plugin, as they won't be able to use their custom public functions with the MySQL natives.
However I will push a fix for this, as the amount of PAWN users is a lot bigger than the amount of C++ gamemode devs, and that fix already was in R33+ anyway.

**Closed** 2018-02-11 20:53 UTC
