### ISSUE TITLE
Pre r40 (?) doesn't work with SAMPCTL

### ISSUE THREAD

**Issue by GoodBlokeAri** [pBlueG/SA-MP-MySQL#209] opened 2019-03-28 11:39 UTC
Spoke to Southclaw and he mentioned it having something to do with the way versioning is on this git?

![error1](https://i.imgur.com/o4KiScH.png "Error 1")
![error2](https://i.imgur.com/F0hC48m.png "Error 2")

**Comment by maddinat0r** [comment] 2019-03-31 08:59
Duplicate of #201. Please use that existing issue for any questions or discussions.

**Closed by maddinat0r** 2019-03-31 08:59 UTC
