### ISSUE TITLE
Bug mysql and y_inline

### ISSUE THREAD

**Issue by MarlonLorran** [pBlueG/SA-MP-MySQL#72] opened 2015-11-08 17:26 UTC
mysql_tquery_inline, mysql_pquery_inline, orm_select_inline and orm_insert_inline does not get executed after /rcon gmx, Why?

Any suggestion? I need fix it.

**Comment by maddinat0r** [comment] 2015-11-12 10:30
Which YSI version are you using? What OS does that bug happen on?

**Comment by MarlonLorran** [comment] 2015-11-12 13:04
I'm using version 4.0.

See an exemple.

```pawn

enum E_PLAYER {
    ORM:ormID,
    name[MAX_PLAYER_NAME]
} new Player[MAX_PLAYERS][E_PLAYER];

public OnPlayerConnect(playerid) {

	// load player data
	LoadPlayer(playerid);
}

LoadPlayer(playerid) {

    new ORM:ormid = Player[playerid][ormID] = orm_create("exemple");
    orm_addvar_string(ormid, Player[playerid][name], MAX_PLAYER_NAME, "name");
    orm_setkey(ormid, "name");

    print("debug 1 OK!");
    inline InformationLoad(pid) {

        switch(orm_errno(Player[pid][ormID])) {

            // user does not exist
            case ERROR_NO_DATA: {
                print("debug 2 OK!");
            }

            // user exists
            case ERROR_OK: {
                print("debug 3 OK!");
            }
        }
    }
    // This function isn't called after GMX
    orm_select_inline(ormid, using inline InformationLoad, "d", playerid);
}
```
After GMX orm_select_inline isn't being called

**Comment by maddinat0r** [comment] 2015-11-13 11:21
Couldn't reproduce it on Windows 8.1.
Code used:
```pawn

new Mysql; 
new ORM:Orm;

new IntVar = 123456;
new Float:FloatVar;


public OnGameModeInit()
{
	mysql_log(LOG_ALL);
    Mysql = mysql_connect(mysql_host, mysql_user, mysql_database, mysql_password);
    if (mysql_errno() != 0)
        return printf("no connection");
   
    SetTimer("TestPublic", 2000, false);
    return 1;
}

forward TestPublic();
public TestPublic()
{
    IntVar = 123456;
	Orm = orm_create("data", Mysql);
	orm_addvar_int(Orm, IntVar, "ints");
	orm_addvar_float(Orm, FloatVar, "floats");
	orm_setkey(Orm, "ints");
	
	inline OrmCallback(number)
	{
	    printf("inline callback called! (%d)", number);
	}
	orm_select_inline(Orm, using inline OrmCallback, "d", 1234);
	return 1;
}


public OnGameModeExit()
{
	orm_destroy(Orm);
	mysql_close(Mysql);
	return 1;
}
```
Output:
```
SA-MP Dedicated Server
----------------------
v0.3z-R4, (C)2005-2014 SA-MP Team

[12:18:00] 
[12:18:00] Server Plugins
[12:18:00] --------------
[12:18:00]  Loading plugin: mysql
[12:18:00]  >> plugin.mysql: R39-3 successfully loaded.
[12:18:00]   Loaded.
[12:18:00]  Loaded 1 plugins.

[12:18:00] 
[12:18:00] Filterscripts
[12:18:00] ---------------
[12:18:00]   Loaded 0 filterscripts.

[12:18:00]  
[12:18:00]  
[12:18:00]  
[12:18:00]  ======================================= 
[12:18:00]  |                                     | 
[12:18:00]  |        YSI version 4.00.0001        | 
[12:18:00]  |        By Alex "Y_Less" Cole        | 
[12:18:00]  |                                     | 
[12:18:00]  ======================================= 
[12:18:00]  
[12:18:00] Number of vehicle models: 0
[12:18:03] inline callback called! (1234)
Console input: gmx
[12:18:18]  
[12:18:18]  
[12:18:18]  
[12:18:18]  ======================================= 
[12:18:18]  |                                     | 
[12:18:18]  |        YSI version 4.00.0001        | 
[12:18:18]  |        By Alex "Y_Less" Cole        | 
[12:18:18]  |                                     | 
[12:18:18]  ======================================= 
[12:18:18]  
[12:18:18] Number of vehicle models: 0
[12:18:21] inline callback called! (1234)
Console input: gmx
[12:18:35]  
[12:18:35]  
[12:18:35]  
[12:18:35]  ======================================= 
[12:18:35]  |                                     | 
[12:18:35]  |        YSI version 4.00.0001        | 
[12:18:35]  |        By Alex "Y_Less" Cole        | 
[12:18:35]  |                                     | 
[12:18:35]  ======================================= 
[12:18:35]  
[12:18:35] Number of vehicle models: 0
[12:18:38] inline callback called! (1234)
```

**Comment by maddinat0r** [comment] 2015-12-05 10:55
I'm closing this, since it seems that this is likely a bug with y_inline itself.

**Closed by maddinat0r** 2015-12-05 10:55 UTC

**Comment by MarlonLorran** [comment] 2015-12-05 15:04
Yes, Excuse-me I forgot reply this, But I've tested with the old version of YS I, and I see that bug really is in new version of YSI. Now I`m using YSI 3.1 and it work perfectly.
