### ISSUE TITLE
mysql_close | Probably BUG

### ISSUE THREAD

**Issue by KrYpToDeN** [pBlueG/SA-MP-MySQL#95] opened 2016-05-06 13:45 UTC
Hello, BlueG.

There is one a little problem with mysql_close(handle) in OnGameModeExit();

If i use it on GameModeExit, i got this warning(during restart/disconnect game server):
[WARNING] CMySQLConnection::Disconnect - no connection available

I'm sure, that i don't use this native anywhere, only in OnGameModeExit.
And also i'm sure, that i have a valid argument inside this native.

Thank you for your plugin! :+1:

**Comment by IstuntmanI** [comment] 2016-05-06 14:50
It has been already reported in issue #91 .

**Comment by maddinat0r** [comment] 2016-05-07 10:00
As @IstuntmanI said, this is a duplicate of #91.

**Closed by maddinat0r** 2016-05-07 10:00 UTC
