### ISSUE TITLE
MySQL crashing issue

### ISSUE THREAD

**Issue by Humza1** [pBlueG/SA-MP-MySQL#128] opened 2016-10-01 07:31 UTC
[09:12:11] [debug] Server crashed due to an unknown error
[09:12:11] [debug] Native backtrace:
[09:12:11] [debug] #0 f73eb9f0 in _Z13GetStackTraceRSt6vectorI10StackFrameSaIS0_EEPv () from plugins/crashdetect.so
[09:12:11] [debug] #1 f73e4a62 in _ZN11CrashDetect20PrintNativeBacktraceERSoPv () from plugins/crashdetect.so
[09:12:11] [debug] #2 f73e5764 in _ZN11CrashDetect20PrintNativeBacktraceEPv () from plugins/crashdetect.so
[09:12:11] [debug] #3 f73e76b4 in _ZN11CrashDetect11OnExceptionEPv () from plugins/crashdetect.so
[09:12:11] [debug] #4 f73eb31d in ?? () from plugins/crashdetect.so
[09:12:11] [debug] #5 f773fd40 in __kernel_rt_sigreturn () from linux-gate.so.1
[09:12:11] [debug] #6 f749f5e8 in ?? () from /lib32/libc.so.6
[09:12:11] [debug] #7 0809571b in ?? () from ./samp03svr
[09:12:11] [debug] #8 f6f99c14 in ?? () from plugins/mysql.so
[09:12:11] [debug] #9 f6fc318b in ?? () from plugins/mysql.so
[09:12:11] [debug] #10 f6fab84b in ?? () from plugins/mysql.so
[09:12:11] [debug] #11 f6fab779 in ?? () from plugins/mysql.so
[09:12:11] [debug] #12 f6facbf4 in ?? () from plugins/mysql.so
[09:12:11] [debug] #13 f6fd39d7 in ProcessTick () from plugins/mysql.so
[09:12:11] [debug] #14 080d1ce2 in ?? () from ./samp03svr
[09:12:11] [debug] #15 080aef6c in ?? () from ./samp03svr
[09:12:11] [debug] #16 080aa13a in ?? () from ./samp03svr
[09:12:11] [debug] #17 f742ca63 in __libc_start_main () from /lib32/libc.so.6

**Comment by maddinat0r** [comment] 2017-06-25 15:42
I have no idea what could've caused this, but I guess it's an AMX function call failing somewhere. I'd need debug logs to further pinpoint the issue, but I think I can close this issue because of my fast response time here (sorry).
If you can manage to reproduce that crash, feel free to reopen it.

**Closed by maddinat0r** 2017-06-25 15:42 UTC
