### ISSUE TITLE
Callbacks not executed until FS reload

### ISSUE THREAD

**Issue by derekmartinez18** [pBlueG/SA-MP-MySQL#54] opened 2015-01-18 21:05 UTC
Hi,

We have the MySQL connect function called in the gamemode and all other source is in filterscripts based on feature. When the mysql_tquery function is called we can see from the MySQL debug logs that the query gets executed successfully and that the callback is called by the plugin. However the callback isn't actually getting executed. It isn't until after the filterscript is reloaded that the callbacks are actually executed. 

I have also tried leaving the MySQL connect in its own filterscript, which produces the same effect.

I have also tried versions: R39-2, R39, and R38. All producing the same effect.

I am running the latest version of the SA-MP server on a Ubuntu 12.04 server with MySQL version 5.5.40.

**Comment by maddinat0r** [comment] 2015-01-18 21:55
Do you have callbacks in other scripts (filterscripts or the main gamemode) which are using the same name as the one you pass to `mysql_tquery`? It might be possible that if two filterscripts have a public function with the same name and you call `mysql_tquery` in filterscript A, the callback in filterscript B gets executed.

**Comment by derekmartinez18** [comment] 2015-01-18 22:08
Nope, they are all uniquely named.

**Comment by maddinat0r** [comment] 2015-01-22 20:13
Could you try downgrading to R34? I currently can't seem to find any possible cause for this.

**Comment by derekmartinez18** [comment] 2015-01-22 21:29
We have downgrading to R34 and everything is working fine.

**Comment by maddinat0r** [comment] 2015-01-23 12:16
I don't have the time taking a closer look at this and fixing that issue, so you'll have to stick to R34. Sorry.

**Comment by bl0wfish** [comment] 2015-02-02 15:51
Same problem here on Ubuntu 14.04. Downgrading to R34 helps, but is not a very satisfying solution.
I hope you can do some further investigations on this.

Thanks.

**Comment by bl0wfish** [comment] 2015-02-04 18:55
You are probably using sampsdk in some other plugin.
Sampsdk hooks amx_FindPublic and makes the order in which the amx objects are iterated through important. Since the data type of m_AmxList in CCallback was changed from list to set this order is different now, which causes trouble.

**Comment by WopsS** [comment] 2015-02-05 06:00
@maddinat0r please leave this issue open. I have this issue right now. It won't process some queries when the gamemode exit.

I'm working for a fix.

**Comment by WopsS** [comment] 2015-02-05 07:37
I fixed it in 003825a636d99006baac5c987f601c0a22325928, but I'm not sure **100%** if I do it in the right way. If I do it right please make a branch for R39-R3 for this fix.

You can do it from the script too.

Just add under **OnGameModeExit** this
```cpp
while (mysql_unprocessed_queries() > 0)
{ }
```

**Comment by maddinat0r** [comment] 2015-02-05 13:50
Okay, seems like that issue really causes much trouble.

@bl0wfish I don't think, that the order in which the AMX instances are iterated through really matters, but I'll take a look at that anyways.

@WopsS No, that can't happen. The plugin halts the PAWN thread as long as _all_ queries (threaded, unthreaded, doesn't matter) are executed.

**Comment by maddinat0r** [comment] 2015-02-05 15:58
Well, I found the cause (faster than I anticipated). The problem is indeed caused by the sampgdk (thus any plugin using it).
Why does this only occur on newer versions and not on R34? @bl0wfish was kind of right, the sampgdk has an own AMX instance (called 'fakeamx') which is also picked up by the MySQL plugin and used for callback processing. But that 'fakeamx' is not really a valid AMX instance and thus returns invalid callback indices. It seems that the 'fakeamx' is always the last AMX instance given to all plugins, thus making the order in which they are stored in plugins important.
However, changing the data container from `set` back to `list` won't completely solve the problem. What if an user passes an invalid callback? That callback will still be processed, since the SAMPGDK hooks some AMX API functions and forces them to always return '0' (which means 'no errors') when called with the 'fakeamx' instance.
Well, what's the best solution? Pretty easy: adding a simple check if the callback index is positive or not (even stated [here](https://github.com/Zeex/sampgdk/blob/master/lib/sampgdk/internal/amxhooks.c#L107-L108) in the SAMPGDK source code).

**Comment by maddinat0r** [comment] 2015-02-05 16:00
I'll create a new branch and apply that fix. I'll also re-apply the R39-3 tag on the new fix, thus I release that fix again as R39-3 (which is currently not really released).

**Comment by maddinat0r** [comment] 2015-02-05 16:35
Does someone has by chance Visual Studio 2012 and the Boost 1.55 (or higher) library (also compiled with VS11) installed on his machine? I don't really want to download gigabytes of stuff only to compile that small fix.

**Comment by WopsS** [comment] 2015-02-05 16:50
@maddinat0r I have Visual Studio 2013 and boost 1.57, that's ok?

**Comment by maddinat0r** [comment] 2015-02-05 17:08
Nope, that won't do.

**Comment by Mellnik** [comment] 2015-02-05 17:37
Aint nobody got time for VS2012.

**Comment by Kar2k** [comment] 2015-02-05 23:56
What sampgdk version is R39-2, R39-3 using?

what about updating sampgdk, older versions are incompatible with newer versions or something?

https://github.com/Zeex/sampgdk/releases

**Comment by maddinat0r** [comment] 2015-02-06 12:52
The MySQL plugin doesn't use the sampgdk, but if at least one other plugin uses the sampgdk, that bug could happen (callbacks being processed with an invalid callback index if the index is not checked before).
This also affects every plugin calling PAWN callbacks, but I guess most of them use the right AMX (or the right iteration order). I hope I'm talking sense here @Zeex?

**Comment by Zeex** [comment] 2015-02-08 10:38
Yes, the fix in https://github.com/pBlueG/SA-MP-MySQL/commit/18417ae3c64409184f5876c68f126008aca0b060 should work. Alternatively you could use another container instead of `std::set` for storing AMX pointers, something that would retain element insertion order (like `std::vector`), and make sure that the gamemode always goes last in there. Though in my opinion it would be much better if the plugin remembered the AMX which issued the query and executed the callback only for that script.

**Comment by maddinat0r** [comment] 2015-02-08 11:12
Good, so I guess this issue is now completely resolved. I won't close this though until @derekmartinez18 or someone else confirms that this bug isn't occuring anymore.
And I already rewrote the callback stuff in R40 and it does exactly what you suggest (remembering which script issued a query and only executing all callback stuff within that AMX) :+1:

**Comment by maddinat0r** [comment] 2015-03-12 23:55
@derekmartinez18 There are now downloads available for all important platforms, so it should be no problem now to update to R39-3 and check if this bug is fixed or not.
If there is no response within two weeks, I'll assume that this issue is resolved.

**Comment by derekmartinez18** [comment] 2015-03-13 00:39
Sorry, got distracted by uni. I've tested it and this problem is resolved. Thank you!

**Comment by maddinat0r** [comment] 2015-03-13 15:48
No problem, thanks for testing and reporting this issue!

**Closed by maddinat0r** 2015-03-13 15:48 UTC
Labels: bug
